# Site settings
baseURL = "//alash3al.com"
languageCode = "en-US"
title = "alash3al - an software engineer"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

publishDir = "docs"


# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2020 Mohamed Al Ashaal"

[params]

  # Metadata for search engines and social sharing
  author = "Mohamed Al Ashaal"
  description = "a software engineer with +7 years experience in building and managing scalable and high performance systems"
  shareImage = "images/picture.jpeg"
  twitterHandle = "m7medalash3al"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/picture.jpeg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Phone"
        url = "tel:+201006343820"

      [[params.links.list1.link]]
        text = "Whatsapp"
        url = "https://api.whatsapp.com/send?phone=+201006343820"

      [[params.links.list1.link]]
        text = "Email"
        url = "mailto:m7medalash3al@gmail.com"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "Github"
        url = "https://github.com/alash3al"

      [[params.links.list2.link]]
        text = "Linkedin"
        url = "https://www.linkedin.com/in/alash3al/"

      [[params.links.list2.link]]
        text = "Twitter"
        url = "https://twitter.com/m7medalash3al"

      [[params.links.list2.link]]
        text = "Facebook"
        url = "https://facebook.com/alash3al"

  # Links List #3
  # [[params.links]]
  #   [params.links.list3]
  #     heading = "Network"

  #     [[params.links.list3.link]]
  #       text = "Link One"
  #       url = "#"

  #     [[params.links.list3.link]]
  #       text = "Link Two"
  #       url = "#"

  #     [[params.links.list3.link]]
  #       text = "Link Three"
  #       url = "#"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
